# This github action will import all data

name: Import Data
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Import Data into DB
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install postgres-client on ubunutu
      run: sudo apt-get update && sudo apt-get install postgresql-client
    - name: PSQL Connect
      run: psql ${{ secrets.PSQL_URL }} -c 'SELECT version()'
    - name: Concat SQL and Execute
      run: |
          cd DATA
          cat *.sql >> all.sql
          echo "**** COMMANDS TO EXCUTE *****"
          echo "$(<all.sql )"
          echo "*****************************"
          psql ${{ secrets.PSQL_URL }} -f all.sql   
