# This github action will create the database

name: Deploy Database
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy PostGreSQL DB
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install postgres-client on ubunutu
      run: sudo apt-get update && sudo apt-get install postgresql-client
    - name: PSQL Connect
      run: SELECT version() | psql postgres://ofnpknxi:mIyip-QntL4PJWk_LINrtBfEklbMkSYt@flora.db.elephantsql.com/ofnpknxi
