# This github action will DROP ALL THE TABLES

name: Drop Tables
on:
  workflow_dispatch:
jobs:
  deploy:
    name: DROP ALL TABLES
    runs-on: ubuntu-latest
    
    steps:
    - name: Install postgres-client on ubunutu
      run: sudo apt-get update && sudo apt-get install postgresql-client
      
    - name: Decode secret
      shell: bash
      env:
        PSQL_URL: ${{ secrets.PSQL_URL }}
      run: |
        echo "${{ secrets.PSQL_URL }}" | base64 --decode
        
    - name: PSQL Connect + DROP TABLES
      run: |
        echo $DECODED
        # echo "PSQL_URL=$(echo ${{ secrets.PSQL_URL }} | base64 --decode)" >> $GITHUB_ENV
        # psql $PSQL_URL -c 'drop schema public cascade;  create schema public;'
  
  
