# This github action will DROP ALL THE TABLES

name: Drop Tables
on:
  workflow_dispatch:
jobs:
  deploy:
    name: DROP ALL TABLES
    runs-on: ubuntu-latest
    
    steps:
    - name: Install postgres-client on ubunutu
      run: sudo apt-get update && sudo apt-get install postgresql-client
    - name: PSQL Connect + DROP TABLES
      run: psql {{ secrets.PSQL_URL }} -c 'drop schema public cascade;  create schema public;'
