# This github action will DROP ALL THE TABLES

name: Drop Tables
on:
  workflow_dispatch:
jobs:
  deploy:
    name: DROP ALL TABLES
    runs-on: ubuntu-latest
    
    steps:
    - name: Install postgres-client on ubunutu
      run: sudo apt-get update && sudo apt-get install postgresql-client

    - uses: akiojin/decode-base64-github-action@v0.1.0
      id: decode-base64
      with:
        base64: ${{ secrets.PSQL_URL }}
    - name: PSQL Connect + DROP TABLES
      run: |
        echo ${{ steps.decode-base64.outputs.decoded }}
        # echo "PSQL_URL=$(echo ${{ secrets.PSQL_URL }} | base64 --decode)" >> $GITHUB_ENV
        # psql $PSQL_URL -c 'drop schema public cascade;  create schema public;'
  
  
