# This github action will draw the ERD from the DDL

# Adapting the code and tools described in this article to make the workflow: 
# https://nsaunders.wordpress.com/2009/01/11/easy-visualisation-of-database-schemas-using-sqlfairy/

name: Generate ERD
on:
  workflow_dispatch:
jobs:
  install:
    name: Generate ERD Diagram
    runs-on: ubuntu-latest
    
    steps: 
    - name: Check out code
      uses: actions/checkout@v4

    - name: Concat SQL
      run: |
          cd DDL
          cat *.sql >> all.sql
          echo "**** COMMANDS TO DRAW *****"
          echo "$(<all.sql )"
          echo "*****************************"
          cd ..
          mv DDL/all.sql ./all.sql

    - name: Export DB
      run: |
        sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y install postgresql
        
        pg_dump -d postgres://ofnpknxi:mIyip-QntL4PJWk_LINrtBfEklbMkSYt@flora.db.elephantsql.com:5432/ofnpknxi > all2.sql
        echo "------------"
        echo "$(<all2.sql )"
        
    - name: Install SQL Fairy
      run: sudo apt-get install sqlfairy

    - name: Run the drawing command
      run: 	sqlt-graph -f MySQL -o erd.png -t png all2.sql

    - name: Upload PNG
      uses: actions/upload-artifact@v3
      with:
        name: erd.png
        path: erd.png
