# This github action will draw the ERD from the DDL

# Adapting the code and tools described in this article to make the workflow: 
# https://ckhung.medium.com/drawing-er-diagram-from-sql-file-alone-e7bef8cfe34b

name: Generate ERD
on:
  workflow_dispatch:
jobs:
  install:
    name: Install the requirements
    runs-on: ubuntu-latest
    
    steps:
    - name: Install erdot
      run: |
              pip3 install ERDot

    - name: Install BurntSushi
      run: |
              sudo apt install -y haskell-stack
              stack upgrade
              wget https://github.com/BurntSushi/erd/archive/refs/heads/master.zip -O erd-master.zip
              unzip erd-master.zip
              cd erd-master/
              stack install

    - name: PHP Steps
      run: |
              mkdir php-steps && cd php-steps
              wget https://gist.githubusercontent.com/ckhung/c208ad5b72e7ebe216fd0bfc7fb1cb7a/raw/498bfb8a66959021ecc941cd4f39f484d28418c8/pmysql.php
              composer require iamcal/sql-parser

              
