name: Orchestation - DEV
 
on:
  workflow_run:
    workflows: [ "Drop Tables", "Execute DDL", "Import Data", "Generate ERD with Fairy SQL" ]
    types:
      - completed
  workflow_dispatch:
jobs:
  work:
    name: Jobs
    runs-on: ubuntu-latest
    steps:
      - run: echo "Orchestration against DEV"
